### ISSUE TITLE
[GDPR09] Minor associated account

### ISSUE THREAD

**Issue by NilHomedes** [AjuntamentdeBarcelona/decidim-module-kids#6]
Reference: GDPR09

**Is your feature request related to a problem? Please describe.**

As a minor participant I can't create an account to participate in the platform. For legal reasons we need the legal guardian consent. 
Futhermore as a legal guardian for a minor, I can't create an account for my son in a safer environment that I can control.

**Describe the solution you'd like**
As a confirmed participant by email account, I want to be able to create an account for my daughter or minor dependant. I will need to

- verify myself through the municipal census
- fill the registration form for the minor account
- add my child's date of birth. This date is important in order to be able to later "Promote minor account to adult account" (Ref: GDPR11)
- verify the minor identity through the municipal census
- accept the declaration of self-responsibility (or terms of use). This text must be customisable from /system 
  
After creating the account, I will be able to change all user profile data of the minor account (name, email, photo, etc.).

I will be able to have several minors' accounts associated with the same profile.

Since the access of minors depends on the context of each organisation, this development must be a module.

**Describe alternatives you've considered**
An other solution could be to have a separate sign-up for minors.

**Does this issue could impact on users private data?**
Yes as it afects to minors data, it is particulary sensitive. 

**Accpetance criteria**
- [x] As a confirmed user I can be able to create a minor account from "My account">"Minors accounts"
- [x] As a confirmed user I have to verify myself thorugh municipal census
- [x] As a confirmed user I can fill in the registration form for my son and define a password
- [x] As a confirmed user I have to verify the identity of the minor through the municipal census. (CP, ID and birthday)
- [x] As a minor registered participant I receive a "Welcome message" after create my account.
- [x] As a minor responsable I can have several minors accounts associated to mine
- [x] As a minor responsable I can change all the data of the user profile from a minor account associated

**Comment by microstudi** [comment]
@NilHomedes I have a question about this.

What's the purpose of adding the adult's ID number? just for information? does it have to be validated?

**Comment by NilHomedes** [comment]
Hi @microstudi we've been reviewing this, and we see that maybe the best option is to ask for a validation through municipal census. The main purpose of that step is to be sure that the adult user is the legal guardian of the minor. But we know that the municipal census won't give us this information, but at least we want to verify the identity of the adult.

**Comment by NilHomedes** [comment]
Finally, we agreed that:

- Legal guardian must be verified through municipal census
- Legal guardian must accept a declaration of self-responsability

These two steps are necessary in order to comply with the GDPR. It talks about making "reasonable efforts" to verify the age of the child and that the legal guardian is the one giving the authorisation. (Art. 8 https://eur-lex.europa.eu/legal-content/ES/TXT/?uri=CELEX%3A32016R0679#d1e2092-1-1)

**Comment by microstudi** [comment]
The create minor wrokflow:
![create_minor_account](https://user-images.githubusercontent.com/1401520/198564384-887a4b95-3cfd-49f4-add9-dffb99d0b24f.png)
